image: docker:20.10.19

stages:
    - Revise
    - Package
    - Staging

Version Up Beta:
  stage: Revise
  script:
    - num=0
    - num=`expr $VERSION_REVISION + 1`
    - echo $num
    - echo "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/variables/VERSION_REVISION"
    - 'docker run alpine/curl --request PUT --header "PRIVATE-TOKEN: $API_TOKEN" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/variables/VERSION_REVISION" --form "value=$num"'
  only:
    - /^release.*$/
    - /^hotfix.*$/
    - develop

Build Container:
  stage: Package
  image: docker:20.10.19
  before_script:
    - cd ./
  script:
    - docker build . -t $CI_REGISTRY/$CI_PROJECT_PATH/prodromoi-web:latest
    - docker build . -t $CI_REGISTRY/$CI_PROJECT_PATH/prodromoi-web:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/prodromoi-web:latest
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/prodromoi-web:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION
    - 'docker run alpine/curl --request PUT --header "PRIVATE-TOKEN: $API_TOKEN" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/variables/WODAN_IMAGE" --form "value=$CI_REGISTRY/$CI_PROJECT_PATH/prodromoi-web:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION"'
  only:
    - /^release.*$/
    - /^hotfix.*$/


Build Container Beta:
  stage: Package
  image: docker:20.10.19
  before_script:
    - cd ./
  script:
    - docker build . -t $CI_REGISTRY/$CI_PROJECT_PATH/prodromoi-web:latest
    - docker build . -t $CI_REGISTRY/$CI_PROJECT_PATH/prodromoi-web:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION-PRE
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/prodromoi-web:latest
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/prodromoi-web:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION-PRE
    - 'docker run alpine/curl --request PUT --header "PRIVATE-TOKEN: $API_TOKEN" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/variables/WODAN_IMAGE" --form "value=$CI_REGISTRY/$CI_PROJECT_PATH/prodromoi-web:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION-PRE"'
  only:
    - develop

# Deploy:
#   stage: Staging
#   needs: ["Build Container"]
#   image: docker/compose:latest
#   tags:
#     - zeke
#   before_script:
#     - cd ./deploy/
#   script:
#     - touch .env
#     - echo "WODAN_IMAGE=$WODAN_IMAGE" >> .env
#     - echo "WODAN_WEB_HOST=$WODAN_WEB_HOST" >> .env
#     - cat .env
#     - docker-compose -f ./stack.yaml config > ./swarm-config.yaml
#     - docker stack deploy --with-registry-auth -c swarm-config.yaml wodan_web_staging
#   only:
#     - /^release.*$/
#     - /^hotfix.*$/
#   environment:
#     name: staging
#     url: https://wodan.zeryter.xyz