stages:
    - Revise
    - Build
    - Release
    - Clean

include:
  - local: '/ci/gitversion-ci-cd-plugin-extension.gitlab-ci.yml' 

GitVersion:
  stage: Revise
  extends: .gitversion_function
  only:
    - /^release.*$/
    - /^hotfix.*$/
    - develop
    - main

Build Container:
  stage: Build
  timeout: 30m
  needs:
    - GitVersion
  before_script:
    - echo "$GitVersion_SemVer"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --name multiarch.$CI_PIPELINE_IID.web --driver docker-container --config ./ci/config.toml
    - docker buildx build --provenance true --builder multiarch.$CI_PIPELINE_IID.web --platform linux/amd64,linux/arm64 --push --platform linux/amd64,linux/arm64 --push --cache-to type=local,dest=/var/image_cache,mode=max --cache-from type=local,src=/var/image_cache -t $CI_REGISTRY/$CI_PROJECT_PATH/web:latest .
    - docker buildx build --provenance true --builder multiarch.$CI_PIPELINE_IID.web --platform linux/amd64,linux/arm64 --push --platform linux/amd64,linux/arm64 --push --cache-to type=local,dest=/var/image_cache,mode=max --cache-from type=local,src=/var/image_cache -t $CI_REGISTRY/$CI_PROJECT_PATH/web:$GitVersion_SemVer .
  after_script:
    - docker buildx rm multiarch.$CI_PIPELINE_IID.web 
  only:
    - /^release.*$/
    - /^hotfix.*$/
    - develop
    - main

Pre-Release:
  stage: Release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - GitVersion
    - Build Container
  script:
    - echo "Pre-release $GitVersion_SemVer"
  release:
    name: 'Pre-Release $GitVersion_SemVer'
    tag_name: $GitVersion_SemVer
    description: |
      New version of Prodromoi web
      
      $GitVersion_InformationalVersion
  only:
    - develop
    - /^release.*$/
    - /^hotfix.*$/

Release:
  stage: Release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - GitVersion
    - Build Container
  script:
    - echo "Pre-release $GitVersion_SemVer"
  release:
    name: 'Release $GitVersion_SemVer'
    tag_name: $GitVersion_SemVer
    description: |
      New version of Prodromoi web

      $GitVersion_InformationalVersion
  only:
    - main

Clean:
  stage: Clean
  timeout: 30m
  needs:
    - Build Container
  script:
    docker system prune -a --force
  only:
    - develop
    - /^release.*$/
    - /^hotfix.*$/
    - main