stages:
    - Revise
    - Build
    - Release

include:
  - local: '/cicd/gitversion-ci-cd-plugin-extension.gitlab-ci.yml' 

GitVersion:
  stage: Revise
  extends: .gitversion_function

Build Container:
  stage: Build
  timeout: 30m
  needs:
    - GitVersion
  before_script:
    - echo "$GitVersion_FullSemVer"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --name multiarch.web --driver docker-container --config ./buildkit/config.toml
    - docker buildx build --provenance false --builder multiarch.web --platform linux/amd64,linux/arm64 --push -t $CI_REGISTRY/$CI_PROJECT_PATH/web:latest .
    - docker buildx build --provenance false --builder multiarch.web --platform linux/amd64,linux/arm64 --push -t $CI_REGISTRY/$CI_PROJECT_PATH/web:$GitVersion_FullSemVer .
  after_script:
    - docker buildx rm multiarch.web 
  only:
    - /^release.*$/
    - /^hotfix.*$/
    - develop

Pre-Release:
  stage: Release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - GitVersion
    - Build Container
  script:
    - echo "Pre-release $GitVersion_FullSemVer"
  release:
    name: 'Pre-Release $GitVersion_FullSemVer'
    tag_name: $GitVersion_FullSemVer
    description: |
      New version of Prodromoi backend services
      
      $GitVersion_InformationalVersion
  only:
    - develop

Release:
  stage: Release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - GitVersion
    - Build Container
  script:
    - echo "Pre-release $GitVersion_FullSemVer"
  release:
    name: 'Release $GitVersion_FullSemVer'
    tag_name: $GitVersion_FullSemVer
    description: |
      New version of Prodromoi backend services

      $GitVersion_InformationalVersion
  only:
    - /^release.*$/
    - /^hotfix.*$/