# https://docs.docker.com/build/buildkit/toml-configuration/
# https://docs.docker.com/build/buildkit/configure/#setting-registry-certificates

debug = true

insecure-entitlements = [ "network.host", "security.insecure" ]

[registry]

  [registry."conreg.samon.lata"]
    ca = ["/etc/docker/certs.d/conreg.samon.lata/ca.crt"]